AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Port.io Integration


Parameters:
  Domain:
    Type: String
    Description: 'Name of Domain'

  System:
    Type: String
    Description: "Name of System"

  Component:
    Type: String
    Description: "Name of Component"

  CodeBranch:
    Type: String
    Description: "Name of GitHub Branch"

  TargetOUIds:
    Type: String
    Description: 'Comma separated list of OUs'

  OrgId:
    Type: String
    Description: 'AWS Organization ID'

  IntegrationIdentifier:
    Type: String
    Description: 'Unique identifier for the integration, e.g. portio-integration'

  OIDCSubject:
    Type: String
    Description: 'The OIDC subject claim to be used in the IAM Role trust policy'
    NoEcho: 'true'

Resources:
  PortIoIntegrationStack:
    Type: AWS::Serverless::Application
    Properties:
      # NOTE: Limitation of SAM
      # ref. https://github.com/aws/serverless-application-model/issues/694
      Location: "https://port-cloudformation-templates.s3.eu-west-1.amazonaws.com/stable/ocean/aws-v3/multi-account-integration.yaml"
      Parameters:
        TargetOUIds: !Ref TargetOUIds
        OrgId: !Ref OrgId
        IntegrationIdentifier: !Ref IntegrationIdentifier
        OIDCSubject: !Ref OIDCSubject
